In [2]:
import numpy as np
#(12,8) split array with possible cases
a=np.arange(1,97).reshape(12,8)
print(a)
print(np.vsplit(a,6))
print(np.vsplit(a,3))
print(np.vsplit(a,4))
print(np.vsplit(a,2))
print(np.hsplit(a,4))
print(np.hsplit(a,2))

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]
 [65 66 67 68 69 70 71 72]
 [73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88]
 [89 90 91 92 93 94 95 96]]
[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]]), array([[17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32]]), array([[33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]]), array([[49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]]), array([[65, 66, 67, 68, 69, 70, 71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80]]), array([[81, 82, 83, 84, 85, 86, 87, 88],
       [89, 90, 91, 92, 93, 94, 95, 96]])]
[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32]]), arr

In [4]:
x = np.arange(1,17).reshape(4,4)#[8 6
#16 14]
print(x[1::2,3:0:-2])
print(x[-3::2,-1:-4:-2])
#[11,9
#15,13]
print(x[2:,2::-2])
print(x[-2:,-2::-2])
#[6,7
#10,11
#14,15]
print(x[1:,1:3])
print(x[-3:,-3:-1])
#reasoning:
#why numpy array ,why not list for storing?
# Speed: NumPy arrays are faster than lists due to C-based optimization.  
# Memory Efficiency: NumPy uses less memory as data is stored contiguously.  
# Vectorized Operations: Supports element-wise operations without loops.  
# Built-in Functions: Provides optimized functions like sum(), mean(), std().  
# Multi-Dimensional Support: Easily handles matrices and tensors.  
# Advanced Operations: Supports linear algebra, ML, and statistics.  
# Broadcasting: Perform arithmetic on entire arrays without iteration.  
# Integration: Works with Pandas, SciPy, TensorFlow, etc.  
# Structured Data: Lists allow mixed types, but NumPy is for numeric data.

[[ 8  6]
 [16 14]]
[[ 8  6]
 [16 14]]
[[11  9]
 [15 13]]
[[11  9]
 [15 13]]
[[ 6  7]
 [10 11]
 [14 15]]
[[ 6  7]
 [10 11]
 [14 15]]
