#### Numpy

In [1]:
# To work with 1d 2d or m-d array
# Mathematical Operations or Numerical Operations

In [2]:
!pip install numpy
!pip install flask

#### Importing Numpy

In [4]:
# To show versions

!pip show numpy
!pip show flask

Name: numpy
Version: 1.26.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYR

In [5]:
# It shows all packages
!pip list

Package                           Version
--------------------------------- ------------
aiobotocore                       2.7.0
aiohttp                           3.9.3
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.12
altair                            5.0.1
anaconda-anon-usage               0.4.3
anaconda-catalogs                 0.2.0
anaconda-client                   1.12.3
anaconda-cloud-auth               0.1.4
anaconda-navigator                2.5.2
anaconda-project                  0.11.1
anyio                             4.2.0
appdirs                           1.4.4
archspec                          0.2.1
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.3
astroid                           2.14.2
astropy                           5.3.4
asttokens                         2.0.5
async-lru                         2.0.4
atomicwrites             

In [7]:
# To see python version
!python --version

Python 3.11.7


In [8]:
# To import package
# import package_name 
# We can also give alias

import numpy as np

In [21]:
# 1 - Dimensional Array
array1 = np.array([10,20,40,50,60,80])
print(type(array1))
print(array1)

array2 = np.array([10.2,20.4,40.6,50.8,60.0,80.1])
print(array2)
print(type(array2))

# Create 1D Array - 8 Elements
array5 = np.array([10,20,40,50,60,70,80])
print(array5)

# For more than 1 dimensional Array we have to start with 2 square braces 
# 2 - Dimensional Array
array3 = np.array([[10,20],[20,40]])
print(array3)
print(type(array3))

# Create 2D Array - 4 rows and 3 columns
array6 = np.array([[10,20,30],[20,30,40],[30,40,50],[40,50,60]])
print(array6)
print(type(array6))

# Create 2D Array - 3 rows and 1 columns
array6 = np.array([[10],[20],[40]])
print(array6)
print(type(array6))

array4 = np.array([[1,2,3,4,5,6,7,8,9],[10,20,30,40,50,60,70,80,90]])
print(array4)
print(type(array4))

<class 'numpy.ndarray'>
[10 20 40 50 60 80]
[10.2 20.4 40.6 50.8 60.  80.1]
<class 'numpy.ndarray'>
[10 20 40 50 60 70 80]
[[10 20]
 [20 40]]
<class 'numpy.ndarray'>
[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]]
<class 'numpy.ndarray'>
[[10]
 [20]
 [40]]
<class 'numpy.ndarray'>
[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]]
<class 'numpy.ndarray'>


#### Specify Datatype

In [26]:
array4 = np.array([1,2,3,4,5,6,7,8,9],dtype="float")
print(array4)

array5 = np.array([10,20,40,50,60,80],dtype="int")
print(array5)

# create an array 2 rows, 4 columns ,dtype = str
array6 = np.array([[10,20,40,50],[60,70,80,90]],dtype="str")
print(array6)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[10 20 40 50 60 80]
[['10' '20' '40' '50']
 ['60' '70' '80' '90']]


#### Different Inspection Method in Array

In [35]:
a = np.array([1,2,3,4,5])

# Checking the variable type of variable
print(type(a))

# Checking the dimension of an array
print(a.ndim)

# Checking the datatype of each elements
print(a.dtype)

# Number of Elements in the array
print(len(a))
print(a.size)

# Memory Byte Allocated to each element of an array
print(a.itemsize)

# Shape of an array
print(a.shape)

<class 'numpy.ndarray'>
1
int32
5
5
4
(5,)


In [41]:
# Create an Element of an array 4 rows, 3 columns, float

a = np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]],dtype=float)

print("Type: ",type(a))
print("Dimension: ",a.ndim)
print("Type Of Element: ",a.dtype)
print("Size: ",len(a))
print("Size: ",a.size)
print("Size of Item: ",a.itemsize)
print("Shape: ",a.shape)

Type:  <class 'numpy.ndarray'>
Dimension:  2
Type Of Element:  float64
Size:  4
Size:  12
Size of Item:  8
Shape:  (4, 3)


#### Different Ways to create the Arrays

In [48]:
# Zeros

o = np.zeros(5)
print(o)

o = np.zeros(5,dtype="int")
print(o)

o = np.zeros((2,4))
print(o)

o = np.zeros((2,4),dtype="int")
print(o)


# Zeros

o = np.ones(5)
print(o)

o = np.ones(5,dtype="int")
print(o)

# full

f = np.full(8,5)
print(f)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]]
[1. 1. 1. 1. 1.]
[1 1 1 1 1]
[5 5 5 5 5 5 5 5]
