In [1]:
# LINSPACE - Generate specified number of elements from the given


import numpy as np

# linspace(start,end,gen)
l=np.linspace(1,10,50)
print(l)
print(l.ndim)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
1


In [9]:
# arange(start,end,step) 
a = np.arange(20,40,2)
print(a)

aa = np.arange(20,100,10)
print(aa)

aaa = np.arange(100)
print(aaa)

aaaa = np.arange(20,35)
print(aaaa)

aaaa=np.arange(100,49,-2)
print(aaaa)

[20 22 24 26 28 30 32 34 36 38]
[20 30 40 50 60 70 80 90]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50]


In [13]:
# reshape - It is used when we have to convert 1 dimensional to another
# Syntax: reshape(shape)
import numpy as np

array=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array.reshape(5,2))

array1=np.arange(1,11)
# Elements : 10 {1*10,10*1,2*5,5*2}
print(array1.reshape(1,10))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


In [18]:
a=np.arange(36,52)
print(a.reshape(4,4))

# a =np.arange(36,52).reshape(4,4)              # print(a)

# Create an array having element from 41 to 49 and give different shapes
a = np.arange(41,49)
print(a.reshape(1,8))
print(a.reshape(8,1))
print(a.reshape(2,4))
print(a.reshape(4,2))

# shape to convert 1D to 2D
# ravel to convert 2D to 1D
# ravel()
b = a.ravel()
print(b)

[[36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]]
[[41 42 43 44 45 46 47 48]]
[[41]
 [42]
 [43]
 [44]
 [45]
 [46]
 [47]
 [48]]
[[41 42 43 44]
 [45 46 47 48]]
[[41 42]
 [43 44]
 [45 46]
 [47 48]]
[41 42 43 44 45 46 47 48]


## Mathematical Operations

In [20]:
# + - * /

# create an array each shoul have shape 2,5

a1 = np.arange(1,11).reshape(2,5)
a2 = np.arange(11,21).reshape(2,5)
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[[12 14 16 18 20]
 [22 24 26 28 30]]
[[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]
[[ 11  24  39  56  75]
 [ 96 119 144 171 200]]
[[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]
 [0.375      0.41176471 0.44444444 0.47368421 0.5       ]]


In [27]:
import numpy as np

a1 = np.arange(1,17).reshape(4,4)

# Aggregate Methos=ds or Functions
print(a1.min())
print(a1.max())
print(a1.sum())
print(a1.mean())
# print(a1.mode())
# print(a1.median())
print(a1.std())

1
16
136
8.5
4.6097722286464435


In [32]:
# Universal Methods/ Functions
print(np.sqrt(a1))
print(np.log(a1))
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]
 [3.60555128 3.74165739 3.87298335 4.        ]]
[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527 2.48490665]
 [2.56494936 2.63905733 2.7080502  2.77258872]]
[[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825]
 [ 0.41211849 -0.54402111 -0.99999021 -0.53657292]
 [ 0.42016704  0.99060736  0.65028784 -0.28790332]]
[[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225 -0.14550003]
 [-0.91113026 -0.83907153  0.0044257   0.84385396]
 [ 0.90744678  0.13673722 -0.75968791 -0.95765948]]
[[ 1.55740772e+00 -2.18503986e+00 -1.42546543e-01  1.15782128e+00]
 [-3.38051501e+00 -2.91006191e-01  8.71447983e-01 -6.79971146e+00]
 [-4.52315659e-01  6.48360827e-01 -2.25950846e+02 -6.35859929e-01]
 [ 4.630211

## Indexing and Slicing on 1D Array

In [39]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

# Positive Indexing
print(a[0])
print(a[1])

# Negative Indexing
print(a[-1])
print(a[-2])

# Printing number 8 using -ve as well as +ve
print(a[7])
print(a[-3])

[ 1  2  3  4  5  6  7  8  9 10]
1
2
10
9
8
8


## Slicing

In [48]:
# Syntax: a[start:end:step]

# Positive - print 3,4,5,6
print(a[2:6])

# Print First 5
print(a[:5])

# Print Last 4
print(a[6:10])

[3 4 5 6]
[1 2 3 4 5]
[ 7  8  9 10]


In [51]:
print(a[2:7:2])
print(a[:6:2])

[3 5 7]
[1 3 5]


In [73]:
## Reversing

# 5432
# 85543
# 3542
# 841
# 33

a=np.array([1,2,3,4,5,5,8,3])
print(a[-4:-8:-1])
print(a[-2:-7:-1])
print(a[-1:-8:-2])
print(a[-2:-9:-3])
print(a[-1:-8:-5])

print(a[4:0:-1])
print(a[6:1:-1])
print(a[8:0:-2])
print(a[6::-3])
print(a[8:1:-5])

[5 4 3 2]
[8 5 5 4 3]
[3 5 4 2]
[8 4 1]
[3 3]
[5 4 3 2]
[8 5 5 4 3]
[3 5 4 2]
[8 4 1]
[3 3]


In [1]:
import numpy as np
x=np.arange(1,17).reshape(4,4)
print(x)
print(x[2,2])
#8
print(x[1,3])
#5
print(x[1,0])
#3
print(x[0,2])
#9
print(x[-2,-4])
#8
print(x[-3,-1])
#5
print(x[-3,-4])
#3
print(x[-4,-2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
11
8
5
3
9
8
5
3


In [7]:
#slicing for 2d array
print(x)
#positive slicing
#syntax for positive
#x[row_slicing,column slicing]
#x[start:end:step,start:end:step]
#[6,7,10,11,14,15]
print(x[1:4,1:3])
print(x[0:2,1:3])
print(x[1:3,0:3])
print(x[0:3,0:3:2])
print(x[1:4:2,1:4:2])
print(x[2:4,1:3])

print(x[:3,1::2])
print(x[:3,:3:2])
print(x[1::2,1::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6  7]
 [10 11]
 [14 15]]
[[2 3]
 [6 7]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 6  8]
 [14 16]]
[[10 11]
 [14 15]]
[[ 2  4]
 [ 6  8]
 [10 12]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 6  8]
 [14 16]]


#### Negative Slicing in 2D Array

In [4]:
import numpy as np
x=np.arange(1,17).reshape(4,4)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [6]:
print(x[-3:-1,-4:-1])

[[ 5  6  7]
 [ 9 10 11]]


In [17]:
print(x[-3:,-3:-1])
print(x[-4:-2,-3:-1])
print(x[-4:-2,-3::2])
print(x[::3,::2])
print(x[::3,::2])

[[ 6  7]
 [10 11]
 [14 15]]
[[2 3]
 [6 7]]
[[2 4]
 [6 8]]
[[ 1  3]
 [13 15]]


### Reversing 2D Array

#### Positive Indexing and Negative Indexing

In [40]:
# Example:
# [[ 1  2  3  4]
# [ 5  6  7  8]
# [ 9 10 11 12]
# [13 14 15 16]]

# [[13 14 15]
# [ 9 10 11]]

print(x[3:1:-1,0:3])
print(x[-1:-3:-1,-4:-1])

# [[6,7,8]
# [2,3,4]]

print(x[1::-1,1:])
print(x[-3::-1,-3:])

print(x[:2,3:0:-1])
print(x[:-2,-1:-4:-1])

# [[8,6]
[16,14]]

# [[11,9]
[15,13]]

# [[6,7]
[10,11]
[14,15]]

# Reasoning: Why we have to use numpy array instead of list for storing??

[[13 14 15]
 [ 9 10 11]]
[[13 14 15]
 [ 9 10 11]]
[[6 7 8]
 [2 3 4]]
[[6 7 8]
 [2 3 4]]
[[4 3 2]
 [8 7 6]]
[[4 3 2]
 [8 7 6]]


#### Iterating through the array

#### For 1D Array

In [43]:
a = np.arange(1,17)
print(a)

for i in a:
    print(i)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


#### For 2D Array

In [56]:
import numpy
a = np.arange(1,17)
print(a)

for i in a:
    print(i)
    for j in i:
        print(j)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1


TypeError: 'numpy.int32' object is not iterable

# Stacking

## Horizontal Stacking

In [62]:
a=np.arange(6).reshape(3,2)
print(a)
b=np.arange(6,12).reshape(3,2)
print(b)

h = np.hstack((a,b))
print("hstack\n",h)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
hstack
 [[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


## Vertical Stacking

In [63]:
v = np.vstack((a,b))
print("vstack\n",v)

vstack
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


## Splitting of an Array

In [77]:
import numpy as np
a = np.arange(30).reshape(2,15)
print(a)

# Horizontal Splitting
a = np.hsplit(a,3)
print(a)


# Create an Array it should have 8 rows and 4 columns

a = np.arange(1,33).reshape(8,4)
print(a)

# Vertical Splitting
a1 = np.vsplit(a,4)
print(a1)

# Horizontal Splitting
a2 = np.hsplit(a,2)
print(a2)

# Create an Array it should have 12 rows and 8 columns
# Split array with all possible cases

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20],
       [21, 22, 23, 24]]), array([[25, 26, 27, 28],
       [29, 30, 31, 32]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22],
       [25, 26],
       [29, 30]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24],
       [27, 28],
       [31, 32]])]
